# Generated by Django 4.1.3 on 2022-11-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='article',
            new_name='photo',
        ),
    ]
